AWSTemplateFormatVersion: 2010-09-09
Description: Reference for a DevSecOps Golden AMI Pipeline
Parameters:
  AMZL2ParentImageId:
    Description: AMI ID of an Amazon Linux 2 AMI to server as the parent for the pipeline
    Type: String
  ImageBuildSecGroupIds:
    Description: Security Group to be used for EC2 Instances
    Type: List<AWS::EC2::SecurityGroup::Id>
  ImageBuilderSubnetId:
    Description: Prefix to be used for the logging bucket name
    Type: AWS::EC2::Subnet::Id
  AwsAccountDistroList:
    Description: Accounts to Distribute
    Type: List<Number>
Resources:
  EC2ImageBuilderLogginBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'aws:arn'
  EC2ImageBuilderRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  EC2ImageBuilderRolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: AccessToS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:PutObject'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref EC2ImageBuilderLogginBucket
                  - /
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref EC2ImageBuilderLogginBucket
                  - /*
      Roles:
        - !Ref EC2ImageBuilderRole
  EC2ImageBuilderInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EC2ImageBuilderRole

  AmazonLinux2GoldenAMIPipeline:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: AmazonLinux2PipelineV2
      Description: Amazon Linux 2 Golden AMI
      ImageRecipeArn: !Ref AmazonLinux2GoldenAMIImageRecipe
      DistributionConfigurationArn: !Ref AmazonLinux2GoldenAMIDistributionConfiguration
      InfrastructureConfigurationArn: !Ref AmazonLinux2GoldenAMInfrastructureConfiguration
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: 90
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_ONLY
        ScheduleExpression: cron(0 0 * * 0)
      Status: ENABLED
      Tags:
        Name: AmazonLinux2GoldenAMIPipeline
  AmazonLinux2GoldenAMIImageRecipe:
    Type: 'AWS::ImageBuilder::ImageRecipe'
    Properties:
      Name: AmazonLinux2GoldenAMIImageRecipe
      Description: Amazon Linux 2 Image Recipe
      ParentImage: !Ref AMZL2ParentImageId
      Components:
        - ComponentArn: !Sub 'arn:aws:imagebuilder:${AWS::Region}:aws:component/stig-build-linux-high/2.5.0/1'
        - ComponentArn: !Ref AmazonLinux2GoldenAMICVERemediationComponent
      Version: 1.0.0
  AmazonLinux2GoldenAMIDistributionConfiguration:
    Type: 'AWS::ImageBuilder::DistributionConfiguration'
    Properties:
      Name: AmazonLinux2GoldenAMIDistributionConfiguration
      Description: Amazon Linux 2 Golden AMI Distribution Configuration
      Distributions:
        - Region: us-east-1
          AmiDistributionConfiguration:
            Name: 'ami-amazonlinux2-1 {{ imagebuilder:buildDate }}'
            Description: Amazon Linux 2 Golden AMI
            AmiTags:
              AmiTagKey: ami-tag-key
            LaunchPermissionConfiguration:
              UserIds: !Ref AwsAccountDistroList
        - Region: us-east-2
          AmiDistributionConfiguration:
            Name: 'ami-amazonlinux2-1 {{ imagebuilder:buildDate }}'
            Description: Amazon Linux 2 Golden AMI
            AmiTags:
              AmiTagKey: ami-tag-key
            LaunchPermissionConfiguration:
              UserIds: !Ref AwsAccountDistroList
      Tags:
        Name: AmazonLinux2GoldenAMIPipeline
  AmazonLinux2GoldenAMInfrastructureConfiguration:
    Type: 'AWS::ImageBuilder::InfrastructureConfiguration'
    Properties:
      Name: AmazonLinux2GoldenAMInfrastructureConfiguration
      Description: Amazon Linux 2 Golden AMI Infrastructure Configuration
      InstanceProfileName: !Ref EC2ImageBuilderInstanceProfile
      Logging:
        S3Logs:
          S3BucketName: !Ref EC2ImageBuilderLogginBucket
      SecurityGroupIds: !Ref ImageBuildSecGroupIds
      SubnetId: !Ref ImageBuilderSubnetId
      TerminateInstanceOnFailure: true
      SnsTopicArn: !Ref pSnsTopicArn
      Tags:
        Name: AmazonLinux2GoldenAMIPipeline
  AmazonLinux2GoldenAMICVERemediationComponent:
    Type: 'AWS::ImageBuilder::Component'
    Properties:
      Name: AmazonLinux2GoldenAMICVERemediationComponent
      Description: CVE Remediation via OS Update
      Platform: Linux
      Version: 1.0.0
      Data: |
        name: UpdateAmazonLinuxKernel
        description: This is hello world testing document.
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: BuildUpdateKernel
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      yum update -y

          - name: validate
            steps:
              - name: ValidateUpdateKernel
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Empty! Validate."

          - name: test
            steps:
              - name: TestUpdateKernel
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Empty! Test."
      Tags:
        Name: AmazonLinux2GoldenAMIPipeline