version: 0.2

phases:
  install:
    commands:
      - apt update && apt install -y jq
      - pip3 install --upgrade pip
      - pip3 install boto3
      - pip3 install detect-secrets
      - cp ./buildspecs/detect-secrets-ejection.py ./artifacts/
      - cp ./security-hub/secretsAsff.py ./artifacts/
      - cd artifacts
  build:
    commands:
      - detect-secrets scan . --all-files > secret-results.json
      - jq . secret-results.json
      - python3 detect-secrets-ejection.py
      - echo detect-secrets scan completed on `date`
  post_build:
    commands:
      - python3 secretsAsff.py
      - echo Security Hub script executed on `date` review the findings there