version: 0.2

phases:
  install:
    commands:
      - apt update && apt install -y jq
      - pip3 install --upgrade pip
      - pip3 install boto3
      - cp ./security-hub/tflintAsff.py ./artifacts/
      - cd artifacts
  build:
    commands:
      - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && rm tflint.zip
      - ./tflint -f=json . > tflint-findings.json
      - echo TFLint check completed on `date`
  post_build:
    commands:
      - jq . tflint-findings.json
      - python3 tflintAsff.py
      - echo Security Hub script executed on `date` review the findings there