version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade pip
      - pip3 install detect-secrets
      - cp ./buildspecs/detect-secrets-ejection.py ./artifacts/
      - cd artifacts
  build:
    commands:
      - detect-secrets scan . --all-files > secret-results.json
      - jq . secret-results.json
      - python3 detect-secrets-ejection.py
  post_build:
    commands:
      - echo detect-secrets scan completed on `date`